# Lecture 5

In [3]:
from datascience import *
import numpy as np

## New material

### Two ways to create tables

**Way 1:** Reading from a file

In [4]:
nba = Table.read_table('https://ucb-dsus-adopters.github.io/materials-fds-assets-v2/lectures/lec05/nba_salaries.csv')
nba.show(6)

**Way 2:** Creating from scratch

In [5]:
streets = make_array('Bancroft', 'Durant', 'Channing', 'Haste')
streets

array(['Bancroft', 'Durant', 'Channing', 'Haste'],
      dtype='<U8')

In [6]:
Table()

In [7]:
southside = Table().with_column('Streets', streets)
southside

Streets
Bancroft
Durant
Channing
Haste

In [8]:
southside.with_column('Blocks from campus', 
                      np.arange(4))

Streets  | Blocks from campus
Bancroft | 0
Durant   | 1
Channing | 2
Haste    | 3

In [11]:
southside_table = Table().with_columns(
    'Streets', streets,
    'Blocks from campus', np.arange(4)
)
southside_table

Streets  | Blocks from campus
Bancroft | 0
Durant   | 1
Channing | 2
Haste    | 3

### W.E.B. DuBois was a data scientist!

In [12]:
du_bois = Table.read_table('https://ucb-dsus-adopters.github.io/materials-fds-assets-v2/lectures/lec05/du_bois.csv')

**Task**: Find the number of rows and the number of columns in this table.

In [18]:
du_bois.num_columns

8

**Task:** Find all of the information (all of the variables) recorded on each "individual" in this table.

In [19]:
du_bois.labels

('CLASS',
 'ACTUAL AVERAGE',
 'RENT',
 'FOOD',
 'CLOTHES',
 'TAXES',
 'OTHER',
 'STATUS')

In [20]:
du_bois

CLASS         | ACTUAL AVERAGE | RENT | FOOD | CLOTHES | TAXES | OTHER | STATUS
100-200       | 139.1          | 0.19 | 0.43 | 0.28    | 0.001 | 0.099 | POOR
200-300       | 249.45         | 0.22 | 0.47 | 0.23    | 0.04  | 0.04  | POOR
300-400       | 335.66         | 0.23 | 0.43 | 0.18    | 0.045 | 0.115 | FAIR
400-500       | 433.82         | 0.18 | 0.37 | 0.15    | 0.055 | 0.245 | FAIR
500-750       | 547            | 0.13 | 0.31 | 0.17    | 0.05  | 0.34  | COMFORTABLE
750-1000      | 880            | 0    | 0.37 | 0.19    | 0.08  | 0.36  | COMFORTABLE
1000 and over | 1125           | 0    | 0.29 | 0.16    | 0.045 | 0.505 | WELL-TO-DO

**Task:** Extract just the information (row(s)) of the families with the highest earning income bracket on average, circa 1900. 
- There are multiple correct ways to do this! See if you can find more than one.

Way 1:

In [23]:
du_bois.where('ACTUAL AVERAGE', are.above(900))

CLASS         | ACTUAL AVERAGE | RENT | FOOD | CLOTHES | TAXES | OTHER | STATUS
1000 and over | 1125           | 0    | 0.29 | 0.16    | 0.045 | 0.505 | WELL-TO-DO

Way 2:

In [29]:
du_bois.sort('ACTUAL AVERAGE', descending=True).take(0)

CLASS         | ACTUAL AVERAGE | RENT | FOOD | CLOTHES | TAXES | OTHER | STATUS
1000 and over | 1125           | 0    | 0.29 | 0.16    | 0.045 | 0.505 | WELL-TO-DO

Discussion [1 min]

**Task:** Based on the relevant variables in the table, estimate the amount of money each that each income class of Black Americans spent on food, circa 1900.
- Discussion [1 min]

In [32]:
du_bois

CLASS         | ACTUAL AVERAGE | RENT | FOOD | CLOTHES | TAXES | OTHER | STATUS
100-200       | 139.1          | 0.19 | 0.43 | 0.28    | 0.001 | 0.099 | POOR
200-300       | 249.45         | 0.22 | 0.47 | 0.23    | 0.04  | 0.04  | POOR
300-400       | 335.66         | 0.23 | 0.43 | 0.18    | 0.045 | 0.115 | FAIR
400-500       | 433.82         | 0.18 | 0.37 | 0.15    | 0.055 | 0.245 | FAIR
500-750       | 547            | 0.13 | 0.31 | 0.17    | 0.05  | 0.34  | COMFORTABLE
750-1000      | 880            | 0    | 0.37 | 0.19    | 0.08  | 0.36  | COMFORTABLE
1000 and over | 1125           | 0    | 0.29 | 0.16    | 0.045 | 0.505 | WELL-TO-DO

In [35]:
food_estimate = du_bois.column('ACTUAL AVERAGE') * du_bois.column('FOOD')

**Task:** Add these estimates to the `du_bois` table as a new column.

In [38]:
du_bois = du_bois.with_column('FOOD ESTIMATE', food_estimate)

____

### Back to the NBA example!

**Task:**
- Extract the rows in the `nba` table that correspond to Stephen Curry from the years 2016, 2017, ..., 2020. 
- Save the table into the name `recent_curry`.

In [44]:
recent_curry = nba.where('season',are.above(2015)).where('name','Stephen Curry')

**Discussion Question 3:** 
- Which of the following two lines of code correctly calculates the average salary of Steph Curry from 2016-2020?
- Use the [Python reference sheet](https://www.data8.org/sp25/reference/) to help you answer!

In [47]:
np.average(recent_curry.select('salary'))

UFuncTypeError: ufunc 'add' did not contain a loop with signature matching types (dtype('<U6'), dtype('<U6')) -> None

In [49]:
np.average(recent_curry.column('salary'))

27725842.199999999