# Lecture 14

In [2]:
from datascience import *
import numpy as np

%matplotlib inline
import matplotlib.pyplot as plots
plots.style.use('fivethirtyeight')

## New material

### Types of samples

In [3]:
united = Table.read_table('https://ucb-dsus-adopters.github.io/materials-fds-assets-v2/lectures/lec14/united.csv')
united = united.with_column('Row', np.arange(united.num_rows)).move_to_start('Row')
united

Row  | Date   | Flight Number | Destination | Delay
0    | 6/1/15 | 73            | HNL         | 257
1    | 6/1/15 | 217           | EWR         | 28
2    | 6/1/15 | 237           | STL         | -3
3    | 6/1/15 | 250           | SAN         | 0
4    | 6/1/15 | 267           | PHL         | 64
5    | 6/1/15 | 273           | SEA         | -6
6    | 6/1/15 | 278           | SEA         | -8
7    | 6/1/15 | 292           | EWR         | 12
8    | 6/1/15 | 300           | HNL         | 20
9    | 6/1/15 | 317           | IND         | -10
... (13815 rows omitted)

#### **Task**: Take a convenience sample of size 5 from the `united` table.

In [4]:
united.take(np.arange(5))

Row  | Date   | Flight Number | Destination | Delay
0    | 6/1/15 | 73            | HNL         | 257
1    | 6/1/15 | 217           | EWR         | 28
2    | 6/1/15 | 237           | STL         | -3
3    | 6/1/15 | 250           | SAN         | 0
4    | 6/1/15 | 267           | PHL         | 64

#### **Task**: Take some *determinstic* samples of 5 rows from the `united` table.

In [ ]:
united.where('Destination', 'JFK').take(np.arange(5))

In [ ]:
united.take(np.arange(start = 75, stop = 100, step = 5))

In [ ]:
united.take(make_array(100,217,324,432,510))

#### **Task**: Take some *random* samples of 5 rows from the `united` table.

##### Way 1: randomly pick a starting point and pick every 5th row from that point

In [ ]:
start = np.random.choice(np.arange(1000))

In [ ]:
start

In [ ]:
random_sample_1 = united.take(np.arange(start, stop=start + 25, step=5))
random_sample_1

##### Way 2: pick five rows at random

In [ ]:
united.sample(k=5, with_replacement=False)

**STOP**

### Distributions also apply to random quantities

In [ ]:
die = Table().with_column('Face', np.arange(1, 7))
die

In [ ]:
die.hist(bins = make_array(1,2,3,4,5,6,7),unit = 'spot')
print('Each spot has an equal chance of being rolled')

In [ ]:
die.sample(10).hist(bins = make_array(1,2,3,4,5,6,7),unit = 'spot')
print('This distribution will vary each time you run this code!')

**STOP**

### The LLN applies to empirical distributions

#### **Task (distributions)**: Create:
- The theoretical probability distribution of a six-sided die
- The observed probability distribution of a six-sided die after: 10, 100, 1,000 and 10,000 rolls.

**Theoretical distribution**

In [ ]:
die.hist(bins = make_array(1,2,3,4,5,6,7),unit = 'spot')
print('Each spot has an equal chance of being rolled')

**Observed distributions**

In [ ]:
die.sample(5).hist(bins = make_array(1,2,3,4,5,6,7),unit = 'spot')

In [ ]:
def observed_die_distribution(k):
    observed_die_rolls = die.sample(k)
    observed_die_rolls.hist(bins = make_array(1,2,3,4,5,6,7),unit = 'spot')

In [ ]:
observed_die_distribution(10)
print("This doesn't look much like the theoretical distribution!")

In [ ]:
observed_die_distribution(100)
print('This looks closer to the theoretical distribution!')

In [ ]:
observed_die_distribution(1000)
print('This looks much more like the theoretical distribution!')

In [ ]:
observed_die_distribution(10000)
print('This looks a lot like the theoretical distribution!')

**STOP**

#### **Task (quantities)**: Find or create
- The median delay time (in minutes) across all United flights from 6/1/15 to 8/9/15.
- The observed distribution of median delay times after taking samples (*with replacement*) of: 10, 100, 1,000 and 10,000 randomly sampled flights.

In [ ]:
np.median(united.column('Delay'))

In [ ]:
np.median(united.sample(10).column('Delay'))

In [ ]:
def observed_sample_median(sample_size):
    return np.median(united.sample(sample_size).column('Delay'))

In [ ]:
observed_sample_median(100)

##### **Discussion** [1 min]: 
- What are the data type(s) of the input?
- What is the data type of the output?

In [ ]:
def observed_sample_median_distribution(repetition_size, sample_size):

    observed_sample_medians = make_array()

    for i in np.arange(repetition_size):
        new_median = observed_sample_median(sample_size)
        observed_sample_medians = np.append(observed_sample_medians, new_median)

    return observed_sample_medians

##### **Discussion** [1 min]: How should I set the arguments to this function so that the LLN is invoked?

In [ ]:
# results = observed_sample_median_distribution(repetition_size=,sample_size=)

In [ ]:
Table().with_column('Sample medians', results).hist()

## Review
- conducted at https://pollev.com/jeremysanchez.