# Lecture 11

In [2]:
from datascience import *
import numpy as np

%matplotlib inline
import matplotlib.pyplot as plots
plots.style.use('fivethirtyeight')
import warnings
warnings.simplefilter(action='ignore',category=np.exceptions.VisibleDeprecationWarning)

## New material

### One-column groups

In [3]:
cones = Table.read_table('https://ucb-dsus-adopters.github.io/materials-fds-assets-v2/lectures/lec11/cones.csv')
cones

Flavor     | Color       | Price
strawberry | pink        | 3.55
chocolate  | light brown | 4.75
chocolate  | dark brown  | 5.25
strawberry | pink        | 5.25
chocolate  | dark brown  | 5.25
bubblegum  | pink        | 4.75

In [4]:
cones.group('Flavor')

Flavor     | count
bubblegum  | 1
chocolate  | 3
strawberry | 2

In [6]:
cones.group('Flavor', np.average)

Flavor     | Color average | Price average
bubblegum  |               | 4.75
chocolate  |               | 5.08333
strawberry |               | 4.4

In [12]:
cones.drop('Color').group('Flavor', collect = np.average)

Flavor     | count
bubblegum  | 1
chocolate  | 3
strawberry | 2

### Cross-classify with **two-group columns**

In [13]:
cones = Table.read_table("https://ucb-dsus-adopters.github.io/materials-fds-assets-v2/lectures/lec11/cones.csv")
cones

Flavor     | Color       | Price
strawberry | pink        | 3.55
chocolate  | light brown | 4.75
chocolate  | dark brown  | 5.25
strawberry | pink        | 5.25
chocolate  | dark brown  | 5.25
bubblegum  | pink        | 4.75

In [14]:
cones.group(['Flavor','Color'])

Flavor     | Color       | count
bubblegum  | pink        | 1
chocolate  | dark brown  | 2
chocolate  | light brown | 1
strawberry | pink        | 2

In [15]:
cones.group(['Flavor','Color'], np.average)

Flavor     | Color       | Price average
bubblegum  | pink        | 4.75
chocolate  | dark brown  | 5.25
chocolate  | light brown | 4.75
strawberry | pink        | 4.4

### Cross-classify with **pivoting**

In [18]:
cones.pivot('Flavor','Color')

Color       | bubblegum | chocolate | strawberry
dark brown  | 0         | 2         | 0
light brown | 0         | 1         | 0
pink        | 1         | 0         | 2

In [22]:
cones.pivot('Flavor','Color','Price',np.average)

Color       | bubblegum | chocolate | strawberry
dark brown  | 0         | 5.25      | 0
light brown | 0         | 4.75      | 0
pink        | 4.75      | 0         | 4.4

_______

### Know when to use grouping vs. pivoting!

In [23]:
# https://corgis-edu.github.io/corgis/csv/skyscrapers/
skyscrapers = Table.read_table('https://ucb-dsus-adopters.github.io/materials-fds-assets-v2/lectures/lec11/skyscrapers.csv')
skyscrapers.show(6)

#### **Task:** 
- For each city, find the tallest building per material, as of 2016.

In [26]:
skyscrapers.select('material','city','height').group(['city','material'], max)

city      | material        | height max
Atlanta   | concrete        | 264.25
Atlanta   | mixed/composite | 311.8
Atlanta   | steel           | 169.47
Austin    | concrete        | 208.15
Austin    | steel           | 93.6
Baltimore | concrete        | 161.24
Baltimore | steel           | 155.15
Boston    | concrete        | 121.92
Boston    | mixed/composite | 139
Boston    | steel           | 240.79
... (81 rows omitted)

In [ ]:
skyscrapers.select('material', 'city', 
                   'height').group(['city', 'material'], max)

#### **Task:** 
- For each city, find the height difference between the tallest steel building and the tallest concrete building.

In [27]:
skyscrapers.select('material', 'city', 
                   'height').group(['city', 'material'], max)

city      | material        | height max
Atlanta   | concrete        | 264.25
Atlanta   | mixed/composite | 311.8
Atlanta   | steel           | 169.47
Austin    | concrete        | 208.15
Austin    | steel           | 93.6
Baltimore | concrete        | 161.24
Baltimore | steel           | 155.15
Boston    | concrete        | 121.92
Boston    | mixed/composite | 139
Boston    | steel           | 240.79
... (81 rows omitted)

In [33]:
skyscrapers.select('city', 'material', 
                   'height').pivot('material','city',values = 'height', collect = max)

city       | concrete | mixed/composite | steel
Atlanta    | 264.25   | 311.8           | 169.47
Austin     | 208.15   | 0               | 93.6
Baltimore  | 161.24   | 0               | 155.15
Boston     | 121.92   | 139             | 240.79
Charlotte  | 265.48   | 239.7           | 179.23
Chicago    | 423.22   | 306.94          | 442.14
Cincinnati | 125      | 202.69          | 175
Cleveland  | 125      | 288.65          | 215.8
Columbus   | 79.25    | 0               | 169.3
Dallas     | 176.48   | 280.72          | 270.06
... (25 rows omitted)

In [ ]:
skyscrapers.select('material', 'city', 
                   'height').group(['city', 'material'], max)

In [34]:
skyscrapers_pivoted = skyscrapers.pivot('material', 'city', 
                                        values='height', collect=max)
skyscrapers_pivoted

city       | concrete | mixed/composite | steel
Atlanta    | 264.25   | 311.8           | 169.47
Austin     | 208.15   | 0               | 93.6
Baltimore  | 161.24   | 0               | 155.15
Boston     | 121.92   | 139             | 240.79
Charlotte  | 265.48   | 239.7           | 179.23
Chicago    | 423.22   | 306.94          | 442.14
Cincinnati | 125      | 202.69          | 175
Cleveland  | 125      | 288.65          | 215.8
Columbus   | 79.25    | 0               | 169.3
Dallas     | 176.48   | 280.72          | 270.06
... (25 rows omitted)

In [36]:
skyscrapers_pivoted = skyscrapers_pivoted.with_column(
    'difference', 
    abs(skyscrapers_pivoted.column('steel') - 
        skyscrapers_pivoted.column('concrete'))
)

In [37]:
skyscrapers_pivoted

city       | concrete | mixed/composite | steel  | difference
Atlanta    | 264.25   | 311.8           | 169.47 | 94.78
Austin     | 208.15   | 0               | 93.6   | 114.55
Baltimore  | 161.24   | 0               | 155.15 | 6.09001
Boston     | 121.92   | 139             | 240.79 | 118.87
Charlotte  | 265.48   | 239.7           | 179.23 | 86.25
Chicago    | 423.22   | 306.94          | 442.14 | 18.92
Cincinnati | 125      | 202.69          | 175    | 50
Cleveland  | 125      | 288.65          | 215.8  | 90.8
Columbus   | 79.25    | 0               | 169.3  | 90.05
Dallas     | 176.48   | 280.72          | 270.06 | 93.58
... (25 rows omitted)

In [38]:
skyscrapers_pivoted.sort('difference', descending=True)

city              | concrete | mixed/composite | steel  | difference
Sunny Isles Beach | 196      | 0               | 0      | 196
Las Vegas         | 350.22   | 195.68          | 164.6  | 185.62
Miami Beach       | 170.39   | 0               | 0      | 170.39
Pittsburgh        | 89.3     | 172             | 256.34 | 167.04
Los Angeles       | 145.7    | 118.26          | 310.29 | 164.59
Philadelphia      | 157.89   | 296.73          | 288.04 | 130.15
Boston            | 121.92   | 139             | 240.79 | 118.87
Austin            | 208.15   | 0               | 93.6   | 114.55
Seattle           | 138.69   | 284.38          | 235.31 | 96.62
Atlanta           | 264.25   | 311.8           | 169.47 | 94.78
... (25 rows omitted)

**Task**: Create a visualization of the distribution of material types of buildings among each of San Francisco, New York and Chicago with one of the two cross-classification methods we have used so far.

_______

### Combine information in different tables via **joining**

In [39]:
drinks = Table().with_columns("Drink", make_array('Milk Tea', 'Espresso', 'Latte','Espresso'),
                              "Cafe", make_array('Asha','Strada','Strada','FSM'),
                              "Price", make_array(5.5,1.75,3.25,2))
drinks

Drink    | Cafe   | Price
Milk Tea | Asha   | 5.5
Espresso | Strada | 1.75
Latte    | Strada | 3.25
Espresso | FSM    | 2

In [40]:
discounts = Table().with_columns("Coupon", make_array('10%','25%','5%'),
                                "Location",make_array('Asha','Strada','Asha'))
discounts

Coupon | Location
10%    | Asha
25%    | Strada
5%     | Asha

In [44]:
drinks.join('Cafe',discounts,'Location')

Cafe   | Drink    | Price | Coupon
Asha   | Milk Tea | 5.5   | 10%
Asha   | Milk Tea | 5.5   | 5%
Strada | Espresso | 1.75  | 25%
Strada | Latte    | 3.25  | 25%

In [45]:
discounts.join('Location',drinks,'Cafe')

Location | Coupon | Drink    | Price
Asha     | 10%    | Milk Tea | 5.5
Asha     | 5%     | Milk Tea | 5.5
Strada   | 25%    | Espresso | 1.75
Strada   | 25%    | Latte    | 3.25