# Lecture 10

In [4]:
from datascience import *
import numpy as np

%matplotlib inline
import matplotlib.pyplot as plots
plots.style.use('fivethirtyeight')
import warnings
warnings.simplefilter(action='ignore',category=np.exceptions.VisibleDeprecationWarning)

## New material

### One-column groups

In [8]:
cones = Table.read_table('https://ucb-dsus-adopters.github.io/materials-fds-assets-v2/lectures/lec10/cones.csv')
cones_without_color = cones.drop('Color')

In [9]:
cones_without_color

Flavor     | Price
strawberry | 3.55
chocolate  | 4.75
chocolate  | 5.25
strawberry | 5.25
chocolate  | 5.25
bubblegum  | 4.75

In [ ]:
cones_without_color

In [14]:
cones_without_color.group('Flavor', np.average)

Flavor     | Price average
bubblegum  | 4.75
chocolate  | 5.08333
strawberry | 4.4

**STOP**

### Two-column groups

In [15]:
cones

Flavor     | Color       | Price
strawberry | pink        | 3.55
chocolate  | light brown | 4.75
chocolate  | dark brown  | 5.25
strawberry | pink        | 5.25
chocolate  | dark brown  | 5.25
bubblegum  | pink        | 4.75

In [23]:
cones.group(['Flavor','Color'],np.average)

Flavor     | Color       | Price average
bubblegum  | pink        | 4.75
chocolate  | dark brown  | 5.25
chocolate  | light brown | 4.75
strawberry | pink        | 4.4

In [26]:
cones.group(['Flavor','Color'], sum)

Flavor     | Color       | Price sum
bubblegum  | pink        | 4.75
chocolate  | dark brown  | 10.5
chocolate  | light brown | 4.75
strawberry | pink        | 8.8

**STOP**

### We can make our own collect functions!

In [27]:
nba = Table.read_table("https://ucb-dsus-adopters.github.io/materials-fds-assets-v2/lectures/lec10/nba_salaries.csv")
nba.show(6)

**Task/Discussion Question**: Write a function called `average_in_millions` which:
- finds the average of a set of numbers, `values`
- divides this average by 1 million.

____

## Review

- Conducted at https://pollev.com/jeremysanchez

## Challenge Tasks

### **Challenge Task (`nba` dataset)**: Find the five teams paying the highest average salary (in millions) in 2010.
- Your results should be in the form of a table with 5 rows and 2 columns:
    - One column should have the team name
    - The other column should have the average salary for that team, in millions.
- Challenge: Try to only use `Table.select()` or `Table.drop()` *once* in your solution.

#### **Challenge Task (`nba` dataset)** Find the $n$ teams paying the highest average salary (in millions) in season $y$.
- In other words, write code that will produce the table you made above, but for any given $n$ and $y$.
- What's an efficient coding technique we can use to complete this problem (*hint: what did we talk about yesterday*)?